In [55]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import catboost as cb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

In [9]:
df=pd.read_csv('train_Inceptez20.csv')

In [39]:
df.drop('policy_id',axis=1,inplace=True)

In [40]:
X=df.iloc[:,:-1]
y=df.iloc[:,-1]

In [41]:
X.shape

(50000, 42)

In [42]:
y.shape

(50000,)

In [43]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=43,stratify=df['is_claim'])

In [44]:
print('X_train shape :',X_train.shape)
print('X_test shape :',X_test.shape)
print('Y_train shape:',y_train.shape)
print('Y_test shape :',y_test.shape)

X_train shape : (37500, 42)
X_test shape : (12500, 42)
Y_train shape: (37500,)
Y_test shape : (12500,)


In [45]:
y_train[y_train==0].count()/len(y_train)

0.9354133333333333

In [46]:
y_train[y_train==1].count()/len(y_train)

0.06458666666666667

In [70]:
y_train.value_counts()

0    35078
1     2422
Name: is_claim, dtype: int64

## Catboost Iteration 1

In [104]:
# cb_1=cb.CatBoostClassifier(scale_pos_weight=5,class_weights=[1,10])
# cb_1=cb.CatBoostClassifier(class_weights=[1,10])
# cb_1=cb.CatBoostClassifier(scale_pos_weight=20)
# cb_1=cb.CatBoostClassifier(scale_pos_weight=30)
# cb_1=cb.CatBoostClassifier(class_weights=[1,15])
cb_1=cb.CatBoostClassifier(class_weights=[1,25])

In [105]:
cb_naive_model=cb_1.fit(X_train,y_train,cat_features=['area_cluster', 'segment', 'model', 'fuel_type', 'max_torque', 'max_power', 'engine_type', 'is_esc', 'is_adjustable_steering', 'is_tpms', 'is_parking_sensors', 'is_parking_camera', 'rear_brakes_type', 'transmission_type', 'steering_type', 'is_front_fog_lights', 'is_rear_window_wiper', 'is_rear_window_washer', 'is_rear_window_defogger', 'is_brake_assist', 'is_power_door_locks', 'is_central_locking', 'is_power_steering', 'is_driver_seat_height_adjustable', 'is_day_night_rear_view_mirror', 'is_ecw', 'is_speed_alert'])

Learning rate set to 0.048422
0:	learn: 0.6867656	total: 123ms	remaining: 2m 2s
1:	learn: 0.6835768	total: 247ms	remaining: 2m 3s
2:	learn: 0.6775956	total: 374ms	remaining: 2m 4s
3:	learn: 0.6735388	total: 501ms	remaining: 2m 4s
4:	learn: 0.6694222	total: 624ms	remaining: 2m 4s
5:	learn: 0.6673790	total: 660ms	remaining: 1m 49s
6:	learn: 0.6625897	total: 786ms	remaining: 1m 51s
7:	learn: 0.6584777	total: 914ms	remaining: 1m 53s
8:	learn: 0.6560492	total: 1.03s	remaining: 1m 53s
9:	learn: 0.6546260	total: 1.13s	remaining: 1m 52s
10:	learn: 0.6517041	total: 1.25s	remaining: 1m 52s
11:	learn: 0.6506078	total: 1.34s	remaining: 1m 50s
12:	learn: 0.6478377	total: 1.46s	remaining: 1m 51s
13:	learn: 0.6454020	total: 1.58s	remaining: 1m 51s
14:	learn: 0.6435185	total: 1.72s	remaining: 1m 52s
15:	learn: 0.6428119	total: 1.75s	remaining: 1m 47s
16:	learn: 0.6417100	total: 1.84s	remaining: 1m 46s
17:	learn: 0.6398186	total: 1.96s	remaining: 1m 47s
18:	learn: 0.6385489	total: 2.07s	remaining: 1m 4

157:	learn: 0.6044067	total: 15.9s	remaining: 1m 24s
158:	learn: 0.6043401	total: 16.1s	remaining: 1m 25s
159:	learn: 0.6042656	total: 16.2s	remaining: 1m 25s
160:	learn: 0.6040658	total: 16.3s	remaining: 1m 25s
161:	learn: 0.6040566	total: 16.4s	remaining: 1m 24s
162:	learn: 0.6040419	total: 16.4s	remaining: 1m 24s
163:	learn: 0.6039997	total: 16.6s	remaining: 1m 24s
164:	learn: 0.6039663	total: 16.7s	remaining: 1m 24s
165:	learn: 0.6039476	total: 16.8s	remaining: 1m 24s
166:	learn: 0.6038682	total: 16.9s	remaining: 1m 24s
167:	learn: 0.6038577	total: 17s	remaining: 1m 24s
168:	learn: 0.6036263	total: 17.1s	remaining: 1m 24s
169:	learn: 0.6034048	total: 17.2s	remaining: 1m 24s
170:	learn: 0.6032967	total: 17.3s	remaining: 1m 24s
171:	learn: 0.6032460	total: 17.5s	remaining: 1m 24s
172:	learn: 0.6028268	total: 17.6s	remaining: 1m 24s
173:	learn: 0.6028169	total: 17.7s	remaining: 1m 23s
174:	learn: 0.6027747	total: 17.8s	remaining: 1m 23s
175:	learn: 0.6025670	total: 17.9s	remaining: 1m

313:	learn: 0.5722488	total: 33.8s	remaining: 1m 13s
314:	learn: 0.5719691	total: 33.9s	remaining: 1m 13s
315:	learn: 0.5717637	total: 34s	remaining: 1m 13s
316:	learn: 0.5715169	total: 34.2s	remaining: 1m 13s
317:	learn: 0.5712371	total: 34.3s	remaining: 1m 13s
318:	learn: 0.5710962	total: 34.4s	remaining: 1m 13s
319:	learn: 0.5710139	total: 34.5s	remaining: 1m 13s
320:	learn: 0.5707139	total: 34.6s	remaining: 1m 13s
321:	learn: 0.5705393	total: 34.7s	remaining: 1m 13s
322:	learn: 0.5702787	total: 34.8s	remaining: 1m 13s
323:	learn: 0.5700789	total: 35s	remaining: 1m 12s
324:	learn: 0.5699586	total: 35.1s	remaining: 1m 12s
325:	learn: 0.5696605	total: 35.2s	remaining: 1m 12s
326:	learn: 0.5693930	total: 35.4s	remaining: 1m 12s
327:	learn: 0.5692078	total: 35.5s	remaining: 1m 12s
328:	learn: 0.5688898	total: 35.6s	remaining: 1m 12s
329:	learn: 0.5687045	total: 35.7s	remaining: 1m 12s
330:	learn: 0.5684530	total: 35.9s	remaining: 1m 12s
331:	learn: 0.5682405	total: 36s	remaining: 1m 12s

471:	learn: 0.5403541	total: 53.3s	remaining: 59.6s
472:	learn: 0.5401203	total: 53.4s	remaining: 59.5s
473:	learn: 0.5399922	total: 53.6s	remaining: 59.4s
474:	learn: 0.5397149	total: 53.7s	remaining: 59.4s
475:	learn: 0.5395688	total: 53.8s	remaining: 59.2s
476:	learn: 0.5395007	total: 53.9s	remaining: 59.1s
477:	learn: 0.5392745	total: 54.1s	remaining: 59s
478:	learn: 0.5391784	total: 54.2s	remaining: 58.9s
479:	learn: 0.5390037	total: 54.3s	remaining: 58.9s
480:	learn: 0.5388114	total: 54.5s	remaining: 58.8s
481:	learn: 0.5386727	total: 54.6s	remaining: 58.7s
482:	learn: 0.5386041	total: 54.7s	remaining: 58.6s
483:	learn: 0.5385370	total: 54.8s	remaining: 58.4s
484:	learn: 0.5384457	total: 54.9s	remaining: 58.3s
485:	learn: 0.5383563	total: 55.1s	remaining: 58.2s
486:	learn: 0.5382033	total: 55.2s	remaining: 58.1s
487:	learn: 0.5380085	total: 55.3s	remaining: 58s
488:	learn: 0.5379615	total: 55.4s	remaining: 57.9s
489:	learn: 0.5377364	total: 55.5s	remaining: 57.8s
490:	learn: 0.53

631:	learn: 0.5157265	total: 1m 13s	remaining: 42.8s
632:	learn: 0.5156085	total: 1m 13s	remaining: 42.7s
633:	learn: 0.5154663	total: 1m 13s	remaining: 42.6s
634:	learn: 0.5153418	total: 1m 13s	remaining: 42.5s
635:	learn: 0.5152048	total: 1m 14s	remaining: 42.4s
636:	learn: 0.5149223	total: 1m 14s	remaining: 42.2s
637:	learn: 0.5148098	total: 1m 14s	remaining: 42.1s
638:	learn: 0.5147383	total: 1m 14s	remaining: 42s
639:	learn: 0.5144864	total: 1m 14s	remaining: 41.9s
640:	learn: 0.5143232	total: 1m 14s	remaining: 41.8s
641:	learn: 0.5141951	total: 1m 14s	remaining: 41.7s
642:	learn: 0.5141232	total: 1m 14s	remaining: 41.6s
643:	learn: 0.5140728	total: 1m 15s	remaining: 41.5s
644:	learn: 0.5138278	total: 1m 15s	remaining: 41.4s
645:	learn: 0.5135561	total: 1m 15s	remaining: 41.3s
646:	learn: 0.5133383	total: 1m 15s	remaining: 41.1s
647:	learn: 0.5130799	total: 1m 15s	remaining: 41s
648:	learn: 0.5130413	total: 1m 15s	remaining: 40.9s
649:	learn: 0.5130119	total: 1m 15s	remaining: 40.

787:	learn: 0.4917518	total: 1m 33s	remaining: 25.1s
788:	learn: 0.4915627	total: 1m 33s	remaining: 25s
789:	learn: 0.4914746	total: 1m 33s	remaining: 24.9s
790:	learn: 0.4913407	total: 1m 33s	remaining: 24.8s
791:	learn: 0.4912417	total: 1m 33s	remaining: 24.7s
792:	learn: 0.4910250	total: 1m 34s	remaining: 24.5s
793:	learn: 0.4907803	total: 1m 34s	remaining: 24.4s
794:	learn: 0.4906671	total: 1m 34s	remaining: 24.3s
795:	learn: 0.4906023	total: 1m 34s	remaining: 24.2s
796:	learn: 0.4904398	total: 1m 34s	remaining: 24.1s
797:	learn: 0.4903263	total: 1m 34s	remaining: 24s
798:	learn: 0.4901340	total: 1m 34s	remaining: 23.9s
799:	learn: 0.4899597	total: 1m 34s	remaining: 23.7s
800:	learn: 0.4897819	total: 1m 35s	remaining: 23.6s
801:	learn: 0.4897678	total: 1m 35s	remaining: 23.5s
802:	learn: 0.4896386	total: 1m 35s	remaining: 23.4s
803:	learn: 0.4893850	total: 1m 35s	remaining: 23.3s
804:	learn: 0.4892489	total: 1m 35s	remaining: 23.2s
805:	learn: 0.4891081	total: 1m 35s	remaining: 23s

943:	learn: 0.4719341	total: 1m 53s	remaining: 6.74s
944:	learn: 0.4718587	total: 1m 53s	remaining: 6.62s
945:	learn: 0.4717717	total: 1m 53s	remaining: 6.5s
946:	learn: 0.4716193	total: 1m 53s	remaining: 6.38s
947:	learn: 0.4715923	total: 1m 54s	remaining: 6.26s
948:	learn: 0.4715069	total: 1m 54s	remaining: 6.14s
949:	learn: 0.4713665	total: 1m 54s	remaining: 6.02s
950:	learn: 0.4712184	total: 1m 54s	remaining: 5.9s
951:	learn: 0.4711960	total: 1m 54s	remaining: 5.78s
952:	learn: 0.4710974	total: 1m 54s	remaining: 5.66s
953:	learn: 0.4709040	total: 1m 54s	remaining: 5.54s
954:	learn: 0.4708523	total: 1m 54s	remaining: 5.42s
955:	learn: 0.4707471	total: 1m 55s	remaining: 5.3s
956:	learn: 0.4706781	total: 1m 55s	remaining: 5.18s
957:	learn: 0.4704904	total: 1m 55s	remaining: 5.06s
958:	learn: 0.4703276	total: 1m 55s	remaining: 4.94s
959:	learn: 0.4702598	total: 1m 55s	remaining: 4.82s
960:	learn: 0.4702287	total: 1m 55s	remaining: 4.7s
961:	learn: 0.4701394	total: 1m 55s	remaining: 4.5

In [52]:
cb_naive_model.best_score_

{'learn': {'Logloss': 0.20238971654320137}}

In [73]:
cb_naive_model.best_score_ #When scale_pos_weight was 5

{'learn': {'Logloss': 0.429270655786123}}

In [81]:
cb_naive_model.best_score_ #class_weights=[1,10]

{'learn': {'Logloss': 0.4917061768485262}}

In [88]:
cb_naive_model.best_score_ #When scale_pos_weight was 20

{'learn': {'Logloss': 0.48560890020131386}}

In [94]:
cb_naive_model.best_score_ #When scale_pos_weight was 30

{'learn': {'Logloss': 0.45045182130860933}}

In [100]:
cb_naive_model.best_score_ #class_weights=[1,15]

{'learn': {'Logloss': 0.49539548561667696}}

In [106]:
cb_naive_model.best_score_ #class_weights=[1,25]

{'learn': {'Logloss': 0.4659779001563421}}

In [109]:
cb_naive_model_result=cb_naive_model.predict(X_test)

In [57]:
len(cb_naive_model_result)

12500

In [58]:
len(y_test)

12500

In [75]:
confusion_matrix(y_test,cb_naive_model_result)#When scale_pos_weight was 5

array([[11555,   138],
       [  791,    16]], dtype=int64)

In [84]:
confusion_matrix(y_test,cb_naive_model_result) #class_weights=[1,10]

array([[9803, 1890],
       [ 580,  227]], dtype=int64)

In [90]:
confusion_matrix(y_test,cb_naive_model_result)#When scale_pos_weight was 20

array([[6338, 5355],
       [ 289,  518]], dtype=int64)

In [96]:
confusion_matrix(y_test,cb_naive_model_result)#When scale_pos_weight was 30

array([[4569, 7124],
       [ 178,  629]], dtype=int64)

In [102]:
confusion_matrix(y_test,cb_naive_model_result) #class_weights=[1,15]

array([[7710, 3983],
       [ 394,  413]], dtype=int64)

In [110]:
confusion_matrix(y_test,cb_naive_model_result) #class_weights=[1,25]

array([[5396, 6297],
       [ 215,  592]], dtype=int64)

In [62]:
cb_naive_model_result

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [66]:
pd.Series(cb_naive_model_result).unique()

array([0, 1], dtype=int64)

In [67]:
 np.count_nonzero(cb_naive_model_result == 0)

12498

In [68]:
 np.count_nonzero(cb_naive_model_result == 1)

2

In [69]:
f1_score(y_test,cb_naive_model_result) #Naive model f1-score

0.0

In [76]:
f1_score(y_test,cb_naive_model_result) #when scale_pos_weight was 5

0.03329864724245578

In [85]:
f1_score(y_test,cb_naive_model_result) #class_weights=[1,10]

0.15526675786593708

In [91]:
f1_score(y_test,cb_naive_model_result) #when scale_pos_weight was 20

0.15508982035928143

In [97]:
f1_score(y_test,cb_naive_model_result) #when scale_pos_weight was 30

0.1469626168224299

In [103]:
f1_score(y_test,cb_naive_model_result) #class_weights=[1,15]

0.1587545646742264

In [111]:
f1_score(y_test,cb_naive_model_result) #class_weights=[1,25]

0.15384615384615383

## Performing prediction on actual test data

In [112]:
df_test=pd.read_csv('test_Inceptez20.csv')

In [113]:
df_test.shape

(8592, 43)

In [118]:
df_test.drop('policy_id',axis=1,inplace=True)

In [119]:
test_result=cb_naive_model.predict(df_test)

In [121]:
test_result.shape

(8592,)

In [123]:
test_result_df=pd.DataFrame(test_result,columns=['is_claim'])
# test_result

In [125]:
test_result_df.to_csv('CB_submission1.csv')