In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,confusion_matrix

In [11]:
train_df=pd.read_csv('D:\\Saravanesh Personal\\Inceptez\\Hackathon\\ML Hackathon\\encoded_datasets\\encoded_train_df.csv')
val_df=pd.read_csv('D:\\Saravanesh Personal\\Inceptez\\Hackathon\\ML Hackathon\\encoded_datasets\\encoded_val_df.csv')
test_df=pd.read_csv('D:\\Saravanesh Personal\\Inceptez\\Hackathon\\ML Hackathon\\encoded_datasets\\encoded_test_df.csv')

In [12]:
train_df.shape

(37500, 45)

In [37]:
train_df.columns

Index(['area_cluster', 'segment', 'model', 'engine_type', 'policy_tenure',
       'age_of_car', 'age_of_policyholder', 'population_density', 'make',
       'airbags', 'displacement', 'cylinder', 'gear_box', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'ncap_rating', 'is_claim',
       'max_torque', 'max_power', 'fuel_type_Diesel', 'fuel_type_Petrol',
       'is_esc_Yes', 'is_adjustable_steering_Yes', 'is_tpms_Yes',
       'is_parking_sensors_Yes', 'is_parking_camera_Yes',
       'rear_brakes_type_Drum', 'transmission_type_Manual',
       'steering_type_Manual', 'steering_type_Power',
       'is_front_fog_lights_Yes', 'is_rear_window_wiper_Yes',
       'is_rear_window_washer_Yes', 'is_rear_window_defogger_Yes',
       'is_brake_assist_Yes', 'is_power_door_locks_Yes',
       'is_central_locking_Yes', 'is_power_steering_Yes',
       'is_driver_seat_height_adjustable_Yes',
       'is_day_night_rear_view_mirror_Yes', 'is_ecw_Yes',
       'is_speed_alert_Yes'],
     

In [13]:
val_df.shape

(12500, 45)

In [14]:
test_df.shape

(8592, 44)

In [38]:
test_df.columns

Index(['area_cluster', 'segment', 'model', 'engine_type', 'policy_tenure',
       'age_of_car', 'age_of_policyholder', 'population_density', 'make',
       'airbags', 'displacement', 'cylinder', 'gear_box', 'turning_radius',
       'length', 'width', 'height', 'gross_weight', 'ncap_rating',
       'max_torque', 'max_power', 'fuel_type_Diesel', 'fuel_type_Petrol',
       'is_esc_Yes', 'is_adjustable_steering_Yes', 'is_tpms_Yes',
       'is_parking_sensors_Yes', 'is_parking_camera_Yes',
       'rear_brakes_type_Drum', 'transmission_type_Manual',
       'steering_type_Manual', 'steering_type_Power',
       'is_front_fog_lights_Yes', 'is_rear_window_wiper_Yes',
       'is_rear_window_washer_Yes', 'is_rear_window_defogger_Yes',
       'is_brake_assist_Yes', 'is_power_door_locks_Yes',
       'is_central_locking_Yes', 'is_power_steering_Yes',
       'is_driver_seat_height_adjustable_Yes',
       'is_day_night_rear_view_mirror_Yes', 'is_ecw_Yes',
       'is_speed_alert_Yes'],
      dtype='obje

### Perform train,test split - Validation

In [41]:
X_train=train_df.drop(labels=['is_claim'],axis=1)
y_train=train_df['is_claim']

In [42]:
y_train

0        0
1        0
2        0
3        0
4        0
        ..
37495    0
37496    0
37497    0
37498    0
37499    0
Name: is_claim, Length: 37500, dtype: int64

In [43]:
X_val=val_df.drop(labels=['is_claim'],axis=1)
y_val=val_df['is_claim']

In [45]:
y_val

0        0
1        0
2        0
3        0
4        0
        ..
12495    0
12496    1
12497    0
12498    0
12499    0
Name: is_claim, Length: 12500, dtype: int64

In [44]:
print(X_train.shape)
print(y_train.shape)
print(X_val.shape)
print(y_val.shape)

(37500, 44)
(37500,)
(12500, 44)
(12500,)


## Naive Random forest model

In [46]:
rf1=RandomForestClassifier()

In [47]:
rf_model1=rf1.fit(X_train,y_train)

In [48]:
rf_model1_result=rf_model1.predict(X_val)

In [49]:
rf_model1_result

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [50]:
confusion_matrix(y_val,rf_model1_result)

array([[11692,     1],
       [  806,     1]], dtype=int64)

In [51]:
f1_score(y_val,rf_model1_result)

0.002472187886279357

In [52]:
count_1 = np.count_nonzero(rf_model1_result == 1)
count_0 = np.count_nonzero(rf_model1_result == 0)
print("Number of 1s:", count_1)
print("Number of 0s:", count_0)

Number of 1s: 2
Number of 0s: 12498


### Setting class_weight = 'balanced'

In [53]:
rf2=RandomForestClassifier(class_weight='balanced')

In [54]:
rf_model2=rf2.fit(X_train,y_train)

In [55]:
rf_model2_result=rf_model2.predict(X_val)

In [56]:
confusion_matrix(y_val,rf_model2_result)

array([[11693,     0],
       [  807,     0]], dtype=int64)

In [58]:
f1_score(y_val,rf_model2_result)

0.0